services:
  db:
    image: postgres:15-alpine
    container_name: cargo-parts-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cargo_parts
      POSTGRES_USER: cargo
      POSTGRES_PASSWORD: cargo
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Optional: pgAdmin (web UI)
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cargo-parts-pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cargo.parts
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: